### PR TITLE
feat: Add functionality to seed wallets based on BPNs

### PR DESCRIPTION
**Pull request by CDiezRodriguez**
## Description

Seed new wallets for each BPN specified.

## Why

This solution addresses the issue described https://github.com/eclipse-tractusx/tractus-x-umbrella/pull/170.

## Issue Link

Refs: #34 

## Checklist
Please delete options that are not relevant.

- [X] I have followed the contributing guidelines

- [X] I have performed IP checks for added or updated 3rd party libraries

- [X] I have added copyright and license headers, footers (for .md files) or files (for images) //open source requirement

- [X] I have performed a self-review of my own code

- [X] I have successfully tested my changes locally

- [X] I have added tests and updated existing tests that prove my changes work

- [X] I have checked that new and existing tests pass locally with my changes
- [x] I have commented my code, particularly in hard-to-understand areas

### CODE REVIEW

**Review by nitin-vavdiya — CHANGES_REQUESTED** [review]
Please also add tests to verify wallets are created for BPNs which are set as environment variable. Similar to  `WalletTest.verifyBaseWallet`

**Review by nitin-vavdiya — CHANGES_REQUESTED** [review]
Please update README.md, add description of new environment variable

**Review by nitin-vavdiya — APPROVED** [review]
LGTM!

**Review by mgarciaLKS — APPROVED** [review]
LGTM

**Pull request merged**
